### ISSUE TITLE
Constructeurs DataGenerator

### ISSUE THREAD

**Issue by PierreAnken** [aislab-hevs/644-1_DemoApplication-Room#1]
Pourquoi ne pas utiliser les constructeurs avec paramètres?

` ClientEntity client1 = new ClientEntity("m.p@fifa.com", "Michel", "Platini", "michel1");
`

**Comment by ChachaNy** [comment]
C'est aussi possible, dans l'exemple ça a été probablement codé ainsi pour favoriser la clarté.
